spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: ${MULTIPART_FILE_SIZE_THRESHOLD}
      max-file-size: ${MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE}
service-configs:
  keycloak:
    issuer-uri: ${KEYCLOAK_ISSUER_URI}
    jwt-set-uri: ${service-configs.keycloak.issuer-uri}/protocol/openid-connect/certs
  web-client:
    time-response: ${TIME_RESPONSE}
  kinescope:
    load-video-url: ${VIDEO_STORAGE_LOAD_URL}
    v1-video-url: ${VIDEO_STORAGE_V1_URL}
    token: ${VIDEO_STORAGE_TOKEN}
    project-id: ${VIDEO_STORAGE_PROJECT_ID}
  yandex-cloud:
    endpoint: ${YANDEX_CLOUD_ENDPOINT}
    bucket-name: ${YANDEX_CLOUD_BUCKET_NAME}
    access-key: ${YANDEX_CLOUD_ACCESS_KEY}
    secret-key: ${YANDEX_CLOUD_SECRET_KEY}

logging:
  level:
    org.springframework.security.oauth2: DEBUG

